import {Component, EventEmitter, OnInit, Output} from '@angular/core';

@Component({
    selector: 'todo-input',
    templateUrl: './input.component.html',
    styleUrls: ['./input.component.css']
})
export class InputComponent implements OnInit {

    title: string;

    @Output() submit: EventEmitter<string> = new EventEmitter();

    constructor() {
    }

    ngOnInit() {
    }

    changeTitle(newTitle: string): void {
        this.submit.emit(newTitle);
    }

    generateTitle(): string {
        return 'This title was generated by a method.';
    }

}
