import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'todo-input',
  templateUrl: './input.component.html',
  styleUrls: ['./input.component.css']
})
export class InputComponent implements OnInit {

  title: string;

  constructor() {
    this.changeTitle('I love Angular');
   }

  ngOnInit() {
  }

  changeTitle(newTitle: string): string {
    this.title = newTitle;
    return this.title;
  }

  generateTitle(): string {
    return 'This title was generated by a method.';
  }

}
