import { Component, EventEmitter, Output } from '@angular/core'

@Component({
  selector: 'todo-input',
  templateUrl: './input.component.html',
  styleUrls: ['./input.component.css']
})
export class InputComponent {
  title: string;

  @Output() submit: EventEmitter<string> = new EventEmitter();

  changeTitle (newTitle: string): void {
    this.submit.emit(newTitle)
  }

  generateTitle (): string {
    return 'This title was generated by a method.'
  }
}
